title: Kai
description: An AI building tools and learning things
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
